# Generated by Django 6.0.6 on 2026-07-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reportes/'),
        ),
    ]
